[workspace]
members  = [
  '01-hello-world',
  '05-augment-prompt-pirate-tone',
  '05-augment-prompt-spanish-translation',
  '05-augment-prompt-grammar-checker',
  '05-multi-turn-dialog',
  '05-memory-systems',
  '05-system-prompt',
  '05-message-array',
  '06-token-count',
  '06-prepare-data',
  '06-knowledge-chatbot',
  '07-rag-chatbot',
  '08-eval-chatbot',
  '08-trace-generator',
  '09-rewrite-history',
  '10-reduce-hallucinations',
  '11-expand-query',
  '12-multiplication',
  '12-feed-results-back',
  '12-website-reader',
  '12-tools-api',
  '13-agent-loop',
  '13-podcast-agent',
  'helpers',
  'vectordb-macro',
]
resolver = '3'

[workspace.dependencies]
argh         = '0.1'
csv          = '1.4'
duckduckgo   = '0.3'
fancy-regex  = '0.18'
openai-oxide = { version='0.14', features=['responses'], default-features=false }
reqwest      = '0.13'
scraper      = '0.27'
serde        = { version='1', features=['derive'] }
serde_json   = '1'
tokio        = { version='1', features=['fs', 'macros', 'rt-multi-thread', 'sync'] }
