[package]
name    = 'trace-generator'
version = '0.1.0'
edition = '2024'

[dependencies]
csv          = { workspace = true }
eval-chatbot = { path = '../08-eval-chatbot' }
helpers      = { path = '../helpers' }
serde        = { workspace = true }
serde_json   = { workspace = true }
tokio        = { workspace = true }
