[package]
name    = 'agent-loop'
version = '0.1.0'
edition = '2024'

[dependencies]
helpers      = { path = '../helpers' }
openai-oxide = { workspace = true }
reqwest      = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
tokio        = { workspace = true }
tools-api    = { path = '../12-tools-api' }
