[package]
name    = 'vector-db'
version = '0.1.0'
edition = '2024'

[dependencies]
arrow-array  = { workspace = true }
fastembed    = { workspace = true }
lancedb      = { workspace = true }
lzma-sys     = { workspace = true }
marrow       = { workspace = true }
serde        = { workspace = true }
serde_arrow  = { workspace = true }
