[package]
name    = 'eval-chatbot'
version = '0.1.0'
edition = '2024'

[dependencies]
argh         = { workspace = true }
arrow-array  = { workspace = true }
async-openai = { workspace = true }
fastembed    = { workspace = true }
futures      = { workspace = true }
lancedb      = { workspace = true }
lzma-sys     = { workspace = true }
pcre2        = { workspace = true }
serde        = { workspace = true }
tokio        = { workspace = true }
utils        = { path = '../utils' }
vector-db    = { path = '../vector-db' }
