[package]
name    = 'website-reader'
version = '0.1.0'
edition = '2024'

[dependencies]
fancy-regex    = { workspace = true }
multiplication = { path = '../12-multiplication' }
helpers        = { path = '../helpers' }
openai-oxide   = { workspace = true }
reqwest        = { workspace = true }
scraper        = { workspace = true }
tokio          = { workspace = true }
